name: Sync map contract - validator preprod - scheduled

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "bactensor/rail-contracts"
          ref: "master"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "scripts/requirements.txt"
      - name: Install dependencies
        run: python -m pip install -r scripts/requirements.txt
      - name: Sync validator config to contracs
        env:
          RPC_URL: "https://lite.chain.opentensor.ai"
          PRIVATE_KEY: ${{ secrets.MAP_CONTRACT_OWNER_PRIVATE_KEY }}
        run: python scripts/map_cli.py 0x5677287f45bFA462A25C7FCE47EE019A5cf9e0E3 sync --env preprod --service validator
